package-lock.json
package.json
src/App.tsx
src/components/Layout.tsx
src/index.css
src/index.tsx
src/pages/MainPage.tsx
src/store/countStore.ts
src/utils/type.ts
tsconfig.json

- 폴더구조 & 기본 레이아웃 파일
- 관련 라이브러리(axios, styled-component 등등) 설치
- index css 에 color 추가, type.ts 예시 작성
- router 세팅

chore: init setting

---

src/pages/MainPage.tsx

Feature/#2 PR 적용 테스트

---

.gitignore
public/index.html
src/pages/MyPage.tsx

> ex) close #7 
카카오 소셜 로그인 기능을 구현합니다.
>

Feature/#7 카카오 로그인 구현

---

package-lock.json
package.json
src/index.tsx
src/pages/MyPage.tsx

> ex) close #8 
구글 로그인 기능을 구현했습니다.
> 
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?   
구글 클라이언트 아이디와 구글 클라이언트 비밀 키 값 생성할 때 이메일이 필요한데 일단 제가 기존의 사용하던 프로젝트 키 값 가져와서 테스트했습니다. 나중에 공통 이메일 생성해서 새로 프로젝트 만들고 나면 그 때 키 값만 변경하면 될 것 같습니다.

Feature/#8 구글 로그인 구현

---

src/App.tsx
src/components/Experience/KeyWordCircle.tsx
src/components/Experience/YearCircle.tsx
src/pages/ExperienceTest.tsx
src/pages/Experience_new.tsx

#27 
https://github.com/KUSITMS-29th-TEAM-B/Frontend/assets/70904075/6e140b57-d11d-40b4-bbbe-64b680de4d7d
수정해야할 사항
- 큰 원 hover시 작은 원까지 hover 가능하게 확대
- 큰 원 click 시 오른쪽에서 팝업슬라이드

Feat/#27 연도별 인터랙션 애니메이션 수정 

---

package-lock.json
src/components/BubbleChartWithGradient.tsx
src/components/Experience/KeyWordCircle.tsx
src/components/Experience/YearCircle.tsx
src/components/common/ToggleButton.tsx
src/dummy.ts
src/pages/ExperienceTest.tsx
src/pages/Experience_new.tsx
src/pages/ddd.tsx

close #31 
https://github.com/KUSITMS-29th-TEAM-B/Frontend/assets/89841486/70adf676-cb75-4171-b86d-a6734acb2327
>

Feature/#31 연도별 인터랙션 추가

---

src/netlify.toml

Feature/#33 배포 리다이렉트 오류 수정

---

src/components/Experience/KeyWordCircle.tsx
src/components/Experience/YearCircle.tsx
src/components/hooks/useComponentSize.tsx
src/components/hooks/useMoveScroll.tsx
src/pages/ExperiencePage.tsx
src/pages/ExperienceTest.tsx
src/pages/Experience_new.tsx
src/store/selectedStore.ts

Feature/#41 연도별 원 포커징 구현 및 주변 원 인터랙션 추가

---

src/components/Experience/YearCircle.tsx
src/index.css
src/pages/ExperiencePage.tsx

Feature/#54 경험 정리 화면 구현

---

src/components/Experience/KeywordTab.tsx
src/components/Experience/MoreTab.tsx
src/components/Experience/PrimeTagCard.tsx
src/components/Experience/YearList.tsx
src/pages/ExperiencePage.tsx
src/services/Experience/moreData.ts

feat: 더보기 탭 구현

---

package.json
src/pages/SignInPage.tsx
src/pages/SignupPage.tsx
src/services/user.tsx
src/store/userInfo.ts
src/types/user.ts

Feature/#88 로그인 & 회원가입 API 연동

---

package-lock.json
package.json
src/App.tsx
src/components/common/Navbar.tsx
src/pages/ProfilePage.tsx
src/pages/SignInPage.tsx
src/pages/SignupPage.tsx
src/services/cookie.tsx
src/services/router/PrivateRoute.tsx
src/services/router/PublicRoute.tsx
src/services/user.tsx
src/types/user.ts

Feature/#94 로그인 접근 권한, 쿠키 설정

---

src/assets/data/questions.ts

Feature/#96 질문 데이터 수정

---

src/components/JD/ExperienceList.tsx
src/components/JD/JDContainer.tsx
src/pages/JDEditPage.tsx
src/pages/JDListPage.tsx
src/pages/JDPlusPage.tsx
src/pages/ProfilePage.tsx
src/services/jd.tsx
src/types/type.ts

#79 
- JD 공고 등록 및 자기소개서 등록 api 연동
- service/jd.tsx 참고

Feat/#79 JD 공고 등록 및 자기소개서 등록 api 연동

---

package.json

fix: proxy 설정 삭제

---

src/components/JD/Announcement.tsx
src/components/JD/StateBox.tsx
src/pages/JDDetailPage.tsx
src/pages/JDEditPage.tsx
src/pages/JDListPage.tsx
src/services/jd.tsx
src/types/type.ts

Feat/#101 JD 공고 리스트 api get, JD 공고 상세 api get 연동

---

src/components/common/DatePicker.tsx

Fix/#117 datepicker 복구

---

src/components/JD/JDContainer.tsx
src/pages/ApplyEditPage.tsx
src/pages/ApplyPage.tsx
src/pages/InfoPage.tsx
src/pages/JDDetailPage.tsx

#101 
공고 상세보기
이미지 로드 시간이 걸려서 일단 로딩처리 timer로 해뒀어요

Feat/#101 자기소개서 공고 상세보기 , profile loading, 서비스 소개 loading

---

src/components/Experience/KeywordTab.tsx
src/components/Experience/MoreTab.tsx
src/components/Experience/YearCircle.tsx
src/components/Experience/YearList.tsx
src/components/JD/Experience.tsx
src/pages/ExperiencePage.tsx
src/pages/ExperienceWritePage.tsx
src/services/Experience/experienceApi.ts
src/services/Experience/tagApi.tsx
src/store/selectedStore.ts
src/types/experience.ts

Feature/#116 경험시각화 페이지 API 연동

---

package-lock.json
package.json
src/components/Experience/KeywordTab.tsx
src/components/Experience/YearList.tsx
src/components/hooks/useExperienceYearsQuery.tsx
src/components/hooks/useSubTagsQuery.tsx
src/index.tsx
src/pages/ExperiencePage.tsx
src/services/Experience/tagApi.tsx

Fix/# 태그 삭제 후 데이터 갱신 이슈

---

src/components/common/Navbar.tsx
src/components/hooks/useGetUserInfo.tsx
src/pages/ProfileEditPage.tsx
src/pages/ProfilePage.tsx
src/services/user.tsx

Feature/#131 사용자 정보 조회 API 연동

---

src/components/common/Input.tsx
src/components/common/Navbar.tsx
src/pages/ExperienceWritePage.tsx
src/pages/ProfilePage.tsx
src/services/user.tsx

Fix/#139 네브바 사용자 정보 이슈

---

src/pages/ExperienceEditPage.tsx
src/pages/ExperienceWritePage.tsx

Fix/#146 버튼 활성화 조건 수정 및 필수 입력 스타일 추가

---

src/components/JD/ExperienceList.tsx

feat: count 오류 수정

---

src/components/JD/ExpContainer.tsx

feat: chip 수정

---

src/pages/SignInPage.tsx
src/pages/SignupPage.tsx
src/services/user.tsx

Feature/#165 토큰 재발급 api 연동
